objects/Case.object
<CustomObject>
    <fields>
        <fullName>Geolocation__c</fullName>
        <description>The latitude and longitude representing the case location.</description>
        <inlineHelpText>The latitude and longitude representing the case location. Geolocation is used to display the case on a map or calculate the distance for duplicate check evaluation.</inlineHelpText>
        <label>Geolocation</label>
        <scale>15</scale>
        <type>Location</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/X11_Case_Metadata_Type__c.object
<CustomObject>
    <fields>
        <fullName>Case_Record_Type__c</fullName>
        <label>Case Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Street</fullName>
                </value>
                <value>
                    <fullName>Parking</fullName>
                </value>
                <value>
                    <fullName>Public Records Request</fullName>
                </value>
                <value>
                    <fullName>Non-Stormwater Discharges</fullName>
                </value>
                <value>
                    <fullName>Buoys and Nav Aids</fullName>
                </value>
                <value>
                    <fullName>Dead Animal</fullName>
                </value>
                <value>
                    <fullName>Sidewalks</fullName>
                </value>
                <value>
                    <fullName>Pier</fullName>
                </value>
                <value>
                    <fullName>Graffiti</fullName>
                </value>
                <value>
                    <fullName>Broken Parking Meter</fullName>
                </value>
                <value>
                    <fullName>Floating Debris</fullName>
                </value>
                <value>
                    <fullName>Irrigation</fullName>
                </value>
                <value>
                    <fullName>PRA Request</fullName>
                </value>
                <value>
                    <fullName>Storm Damage</fullName>
                </value>
                <value>
                    <fullName>Street Lights</fullName>
                </value>
                <value>
                    <fullName>Vegetation</fullName>
                </value>
                <value>
                    <fullName>Facilities and Equipment</fullName>
                </value>
                <value>
                    <fullName>Traffic Lights Out</fullName>
                </value>
                <value>
                    <fullName>Illegal Dumping</fullName>
                </value>
                <value>
                    <fullName>Homeless Encampment</fullName>
                </value>
                <value>
                    <fullName>Pothole</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Graffiti</fullName>
                </value>
                <value>
                    <fullName>Potholes</fullName>
                </value>
                <value>
                    <fullName>Broken Parking Meter</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Public Records Request</fullName>
                </value>
                <value>
                    <fullName>Dead Animal</fullName>
                </value>
                <value>
                    <fullName>Vegetation</fullName>
                </value>
                <value>
                    <fullName>Irrigation</fullName>
                </value>
                <value>
                    <fullName>Floating Debris</fullName>
                </value>
                <value>
                    <fullName>Street Lights</fullName>
                </value>
                <value>
                    <fullName>Paths and Walkways</fullName>
                </value>
                <value>
                    <fullName>Buoys and Navigational Aids</fullName>
                </value>
                <value>
                    <fullName>Pier</fullName>
                </value>
                <value>
                    <fullName>Illegal Discharge</fullName>
                </value>
                <value>
                    <fullName>Oil Spills/Slicks</fullName>
                </value>
                <value>
                    <fullName>Sewage</fullName>
                </value>
                <value>
                    <fullName>Illegal Maintenance Activity</fullName>
                </value>
                <value>
                    <fullName>Flooded Storm Drain</fullName>
                </value>
                <value>
                    <fullName>Wind Damage</fullName>
                </value>
                <value>
                    <fullName>Storm Damage</fullName>
                </value>
                <value>
                    <fullName>General Parking Question</fullName>
                </value>
                <value>
                    <fullName>Other Parking Issues</fullName>
                </value>
                <value>
                    <fullName>Non-Stormwater Discharges</fullName>
                </value>
                <value>
                    <fullName>Sidewalks</fullName>
                </value>
                <value>
                    <fullName>Facilities and Equipment</fullName>
                </value>
                <value>
                    <fullName>Traffic Lights Out</fullName>
                </value>
                <value>
                    <fullName>Illegal Dumping and Litter</fullName>
                </value>
                <value>
                    <fullName>Homeless Encampment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_UX_Type__c</fullName>
        <label>Case UX Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Car driving by a pothole on the street</fullName>
                </value>
                <value>
                    <fullName>Oversized Vehicles</fullName>
                </value>
                <value>
                    <fullName>Zone Issue</fullName>
                </value>
                <value>
                    <fullName>Quality of Life</fullName>
                </value>
                <value>
                    <fullName>Illegal Use or Activity</fullName>
                </value>
                <value>
                    <fullName>Safety Risk</fullName>
                </value>
                <value>
                    <fullName>Illegal Construction</fullName>
                </value>
                <value>
                    <fullName>Trash Collection Services</fullName>
                </value>
                <value>
                    <fullName>Appointments</fullName>
                </value>
                <value>
                    <fullName>Report</fullName>
                </value>
                <value>
                    <fullName>Curb</fullName>
                </value>
                <value>
                    <fullName>Pothole</fullName>
                </value>
                <value>
                    <fullName>Sidewalk Repair</fullName>
                </value>
                <value>
                    <fullName>Street Light</fullName>
                </value>
                <value>
                    <fullName>Traffic Sign</fullName>
                </value>
                <value>
                    <fullName>Traffic Signal</fullName>
                </value>
                <value>
                    <fullName>Damaged Guardrail</fullName>
                </value>
                <value>
                    <fullName>Faded Striping</fullName>
                </value>
                <value>
                    <fullName>Street Sweeping</fullName>
                </value>
                <value>
                    <fullName>Other street, sidewalk, and light related issue</fullName>
                </value>
                <value>
                    <fullName>Tree Maintenance</fullName>
                </value>
                <value>
                    <fullName>Storm Drain</fullName>
                </value>
                <value>
                    <fullName>Street Flooded</fullName>
                </value>
                <value>
                    <fullName>Illegal Discharge</fullName>
                </value>
                <value>
                    <fullName>Over Irrigation</fullName>
                </value>
                <value>
                    <fullName>Schedule an Appointment for a Passport</fullName>
                </value>
                <value>
                    <fullName>Graffiti</fullName>
                </value>
                <value>
                    <fullName>72 Hour Violation</fullName>
                </value>
                <value>
                    <fullName>PRA</fullName>
                </value>
                <value>
                    <fullName>Public Records Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duplicate_Radious_Miles__c</fullName>
        <formula>X11_Radius_for_Duplicate_Check__c/5280</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duplicate Radious Miles</label>
        <precision>18</precision>
        <scale>18</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X11_Case_Status__c</fullName>
        <label>Case Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Referred</fullName>
                </value>
                <value>
                    <fullName>Pending Work</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Configuration</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Case Metadata Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/X11_Case_DuplicateCheck.cls
public without sharing class X11_Case_DuplicateCheck {

    public static void duplicatecheck(Case csObj){
        String slatitude = String.ValueOf(csObj.Geolocation__latitude__s);
        String slongitude = String.ValueOf(csObj.Geolocation__longitude__s);
        if(slatitude != null && slongitude != null){
        	String sDistance = 'mi';
            Double radius = 100;
            Double radius_ft = radius;
            Double radius_mi = 0.00018939 * radius_ft;
            List<X11_Case_Metadata_Type__c> caseConfigList = [SELECT Id, Case_Record_Type__c, Case_Type__c, X11_Case_Status__c, Duplicate_Radious_Miles__c FROM X11_Case_Metadata_Type__c WHERE Case_UX_Type__c=: csObj.Type LIMIT 1];
            if(caseConfigList.size() > 0 && caseConfigList[0].Duplicate_Radious_Miles__c > 0){
            	radius_mi = Double.valueOf(caseConfigList[0].Duplicate_Radious_Miles__c);
            }
            
            List<String> statusList = new List<String>{'New','In Progress'};
                String queryString = 'Select Id,RecordTypeId,Status,Type,ParentId,Geolocation__c,Geolocation__Latitude__s,Geolocation__Longitude__s from Case';
            String whereCondition = '';
            whereCondition += ' WHERE Id <>\''+csObj.Id+'\'';//Department__c = \''+caseObj.Department__c+'\' AND
            whereCondition += ' AND Type = \''+csObj.Type+'\'';
            whereCondition += ' AND Status IN :statusList';
            whereCondition += ' AND DISTANCE(Geolocation__c, GEOLOCATION(' + csObj.Geolocation__Latitude__s + ', ' + csObj.Geolocation__Longitude__s + ' ), \'mi\') < '+radius_mi;
            whereCondition += ' ORDER BY DISTANCE(Geolocation__c, GEOLOCATION(' + csObj.Geolocation__Latitude__s + ', ' + csObj.Geolocation__Longitude__s + ' ), \'mi\') ASC LIMIT 1';   
            List<Case> parentCaseLst = Database.query(queryString + whereCondition);
            if(parentCaseLst.size() > 0){ 
                csObj.Status = 'Duplicate';
                csObj.ParentId = parentCaseLst[0].Id;
                if(csObj != Null){
                    update csObj;
                }
            }
        }
    }
}