objects/X11_Case_Metadata_Type__c.object
<CustomObject>
    <fields>
        <fullName>Available_for_Portal_User__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Available for Portal User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_UX_Category__c</fullName>
        <label>UX Group</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trash and Maintenance</fullName>
                </value>
                <value>
                    <fullName>Graffiti</fullName>
                </value>
                <value>
                    <fullName>Illegal Dumping</fullName>
                </value>
                <value>
                    <fullName>Parking</fullName>
                </value>
                <value>
                    <fullName>Private Property, Buildings &amp; Construction</fullName>
                </value>
                <value>
                    <fullName>Trash Collection, Recycling &amp; Graffiti</fullName>
                </value>
                <value>
                    <fullName>Streets, Sidewalks &amp; Lights</fullName>
                    <label>Streets, Sidewalks, and Lights</label>
                </value>
                <value>
                    <fullName>Trees &amp; Vegetation</fullName>
                </value>
                <value>
                    <fullName>Water, Sewer &amp; Drains</fullName>
                </value>
                <value>
                    <fullName>Passport Services</fullName>
                </value>
                <value>
                    <fullName>Public Records Request</fullName>
                </value>
                <value>
                    <fullName>Pier and Bay</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>Storm Damage</fullName>
                </value>
                <value>
                    <fullName>Facilities and Equipment</fullName>
                </value>
                <value>
                    <fullName>Non-Stormwater Discharges</fullName>
                </value>
                <value>
                    <fullName>Traffic Lights Out</fullName>
                </value>
                <value>
                    <fullName>Homeless Encampment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_UX_Description__c</fullName>
        <label>UX Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case_UX_Estimation__c</fullName>
        <label>Estimated Resolution Time</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case_UX_Popular_Types__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Popular Case Type?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_UX_Type__c</fullName>
        <label>Case UX Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Car driving by a pothole on the street</fullName>
                </value>
                <value>
                    <fullName>Oversized Vehicles</fullName>
                </value>
                <value>
                    <fullName>Zone Issue</fullName>
                </value>
                <value>
                    <fullName>Quality of Life</fullName>
                </value>
                <value>
                    <fullName>Illegal Use or Activity</fullName>
                </value>
                <value>
                    <fullName>Safety Risk</fullName>
                </value>
                <value>
                    <fullName>Illegal Construction</fullName>
                </value>
                <value>
                    <fullName>Trash Collection Services</fullName>
                </value>
                <value>
                    <fullName>Appointments</fullName>
                </value>
                <value>
                    <fullName>Report</fullName>
                </value>
                <value>
                    <fullName>Curb</fullName>
                </value>
                <value>
                    <fullName>Pothole</fullName>
                </value>
                <value>
                    <fullName>Sidewalk Repair</fullName>
                </value>
                <value>
                    <fullName>Street Light</fullName>
                </value>
                <value>
                    <fullName>Traffic Sign</fullName>
                </value>
                <value>
                    <fullName>Traffic Signal</fullName>
                </value>
                <value>
                    <fullName>Damaged Guardrail</fullName>
                </value>
                <value>
                    <fullName>Faded Striping</fullName>
                </value>
                <value>
                    <fullName>Street Sweeping</fullName>
                </value>
                <value>
                    <fullName>Other street, sidewalk, and light related issue</fullName>
                </value>
                <value>
                    <fullName>Tree Maintenance</fullName>
                </value>
                <value>
                    <fullName>Storm Drain</fullName>
                </value>
                <value>
                    <fullName>Street Flooded</fullName>
                </value>
                <value>
                    <fullName>Illegal Discharge</fullName>
                </value>
                <value>
                    <fullName>Over Irrigation</fullName>
                </value>
                <value>
                    <fullName>Schedule an Appointment for a Passport</fullName>
                </value>
                <value>
                    <fullName>Graffiti</fullName>
                </value>
                <value>
                    <fullName>72 Hour Violation</fullName>
                </value>
                <value>
                    <fullName>PRA</fullName>
                </value>
                <value>
                    <fullName>Public Records Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Display_on_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display on Web?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sequence_on_portal__c</fullName>
        <label>Sequence on portal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Case Configuration</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Case Metadata Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/X11_HomePageController.cls
public without sharing class X11_HomePageController {

    @AuraEnabled
    public static Wrapper getAllCaseConfigurationRecords() {
        Wrapper response = new Wrapper();
        String loggedInUserLincence = [Select Profile.UserLicense.Name from User WHERE Id =: UserInfo.getUserId() LIMIT 1].Profile.UserLicense.Name;
        response.isPortalUser = (System.Label.X11Community_Licenses.contains(loggedInUserLincence));
		response.allCaseConfigurations = new List<CaseConfiguration>();
        response.popularCaseConfigurations = new List<CaseConfiguration>();
        
        Map<String, CaseCategoryConfiguration> caseConfigurationsByCategory = new Map<String, CaseCategoryConfiguration>();
        
        String query =  'SELECT Id, Case_UX_Category__c, Case_UX_Type__c, Case_UX_Description__c, Case_UX_Estimation__c, ' +
            					'Case_UX_Popular_Types__c, Sequence_on_portal__c ' + 
            			'FROM X11_Case_Metadata_Type__c ' + 
            			'WHERE Display_on_Web__c = true ';
        if(response.isPortalUser) {
            query += 'AND Available_for_Portal_User__c = true ';
        }
        
        query += 'ORDER BY Sequence_on_portal__c LIMIT 100';
        
        for(X11_Case_Metadata_Type__c caseMetadataType : Database.query(query)) {
            CaseConfiguration caseConfig = new CaseConfiguration();
            caseConfig.caseId = response.isPortalUser ? X11_Utility.encryptAndEncodeURL(caseMetadataType.Id) : caseMetadataType.Id;
            caseConfig.caseCategory = caseMetadataType.Case_UX_Category__c;
            caseConfig.caseType = caseMetadataType.Case_UX_Type__c;
            caseConfig.caseDescription = caseMetadataType.Case_UX_Description__c;
            caseConfig.caseEstimation = String.valueOf(caseMetadataType.Case_UX_Estimation__c);
            caseConfig.casePopularType = caseMetadataType.Case_UX_Popular_Types__c;
            
            //Add Case Configuration to All Case Configuration List
            response.allCaseConfigurations.add(caseConfig);
            
            //Add Case Configuration in List Grouped by Category
            if(String.isNotBlank(caseConfig.caseCategory)) {
                if(!caseConfigurationsByCategory.containsKey(caseConfig.caseCategory)) {
                    CaseCategoryConfiguration temp = new CaseCategoryConfiguration();
                    temp.caseCategory = caseConfig.caseCategory;
                    temp.caseConfigurations = new List<CaseConfiguration>();
                    caseConfigurationsByCategory.put(caseConfig.caseCategory, temp);
                }
                caseConfigurationsByCategory.get(caseConfig.caseCategory).caseConfigurations.add(caseConfig);
            }
            
            //Add Case Configuration to Popuplar Case Configuration List
            if(caseConfig.casePopularType) {
                response.popularCaseConfigurations.add(caseConfig);
            }
        }
        
        response.caseConfigurationsByCategory = caseConfigurationsByCategory.values();
        
		return response;        
    }
    
    public class Wrapper {
        @AuraEnabled public Boolean isPortalUser;
        @AuraEnabled public List<CaseConfiguration> allCaseConfigurations;
        @AuraEnabled public List<CaseCategoryConfiguration> caseConfigurationsByCategory;
        @AuraEnabled public List<CaseConfiguration> popularCaseConfigurations;
    }
    
    public class CaseCategoryConfiguration {
        @AuraEnabled public String caseCategory;
        @AuraEnabled public List<CaseConfiguration> caseConfigurations;
    }
    
    public class CaseConfiguration {
        @AuraEnabled public String caseId;
        @AuraEnabled public String caseCategory;
        @AuraEnabled public String caseType;
        @AuraEnabled public String caseDescription;
        @AuraEnabled public String caseEstimation;
        @AuraEnabled public Boolean casePopularType;
    }
}